import { appendFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import type { Classification } from "./classifier.js";

export interface Asset {
  name: string;
  type: string;
  location: string;
  status: string;
  status_notes?: string;
  registered_on?: string;
}

export interface AssetsFile {
  version: number;
  assets: Asset[];
}

export function readAssets(path: string): AssetsFile {
  return JSON.parse(readFileSync(path, "utf-8")) as AssetsFile;
}

export function logEvent(logFile: string, entry: Record<string, unknown>): void {
  const line = { ts: new Date().toISOString(), ...entry };
  appendFileSync(logFile, JSON.stringify(line) + "\n");
}

export function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

export interface ReportPaths {
  mdPath: string;
  signalsJsonPath: string;
}

export function writeReports(
  paths: ReportPaths,
  date: string,
  asset: Asset,
  classification: Classification,
): void {
  mkdirSync(dirname(paths.mdPath), { recursive: true });
  const signals = classification.signals;

  const md = [
    `# Asset Signal Report — ${date}`,
    ``,
    `**Asset:** ${asset.name} (${asset.type})`,
    `**Location:** ${asset.location}`,
    `**User status:** ${asset.status}${asset.status_notes ? ` — "${asset.status_notes}"` : ""}`,
    ``,
    `---`,
    ``,
    `## Signals`,
    ``,
    ...(signals.length === 0
      ? [`No signal found — ${classification.recommendation || "no verifiable source"}`]
      : signals.map((s) => {
          const badge =
            s.klass === "Opportunity"
              ? "[Opportunity]"
              : s.klass === "Risk"
                ? "[Risk]"
                : "[Noise]";
          return `### ${badge} ${s.signal}\n\n- **Reason:** ${s.reason}\n- **Source:** ${s.source_url}\n`;
        })),
    ``,
    `## Recommendation`,
    ``,
    classification.recommendation || "No recommendation — see signals above.",
    ``,
    `---`,
    ``,
    `*Generated by the Asset Signal Scout scripted agent (FL-07). Sources are real and scraped live; no numbers were invented. The agent only reports — the user decides.*`,
  ].join("\n");

  writeFileSync(paths.mdPath, md);
  writeFileSync(
    paths.signalsJsonPath,
    JSON.stringify(
      {
        date,
        asset: asset.name,
        classifications: signals.map((s) => ({
          signal: s.signal,
          klass: s.klass,
          reason: s.reason,
          source_url: s.source_url,
        })),
        recommendation: classification.recommendation,
      },
      null,
      2,
    ) + "\n",
  );
}
